#!/usr/bin/env python3
"""Embed Shaders/Fold.metal into a Swift source file.

The Metal compiler ships with Xcode, not with the command line tools, so the
shader cannot be precompiled into a .metallib on a machine that only has the
CLT. Instead the shader is compiled at runtime by MTLDevice, and this script
folds the source text into the binary as a Swift string literal.

Keeping the shader in a real .metal file means it stays editable with syntax
highlighting and stays diffable, while the build still needs nothing but swiftc.
"""

from __future__ import annotations

import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SOURCE = ROOT / "Shaders" / "Fold.metal"
TARGET = ROOT / "Generated" / "FoldShaderSource.swift"


def swift_literal(text: str) -> str:
    """Render `text` as a Swift raw string literal.

    Raw delimiters (``#``) are used so backslashes in the shader need no escaping,
    and any run of ``"#`` inside the shader is broken up defensively.
    """
    safe = text.replace('"#', '"\\#')
    return f'#"""\n{safe}\n"""#'


def main() -> int:
    if not SOURCE.exists():
        print(f"embed_shader: missing {SOURCE}", file=sys.stderr)
        return 1

    text = SOURCE.read_text(encoding="utf-8")
    if "foldVertex" not in text or "foldFragment" not in text:
        print(
            "embed_shader: shader is missing foldVertex/foldFragment; refusing to embed",
            file=sys.stderr,
        )
        return 1

    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text(
        "// Generated by Tools/embed_shader.py from Shaders/Fold.metal.\n"
        "// Do not edit by hand: edit the .metal file and rebuild.\n"
        "\n"
        "/// Metal source for the fold, compiled at runtime by the renderer.\n"
        "enum FoldShaderSource {\n"
        f"    static let text = {swift_literal(text)}\n"
        "}\n",
        encoding="utf-8",
    )
    print(f"embed_shader: wrote {TARGET.relative_to(ROOT)} ({len(text)} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
